### ISSUE TITLE
[Eden] [0003] Consider support for rotary spawns larger than light

### ISSUE THREAD

**Issue by ahtotaat** [mwpowellhtx/KP-Liberation#89] opened 2021-05-13 11:20 UTC
### Basic Information
**Mission version:** s.15
**Map used:** Altis
**Mods used:** CUP Vehicles and it's dependencies
**Dedicated or local game:** MP
**Source of the mission file (URL):** this github repository

### Proposal
Distance between 'light' choppers on the Flight Deck of U.S.S Liberty not sufficient for choppers longer than MH-9 (vanilla) or MH-6 (RHS).

### Individual Things
**Did you edit anything within the mission files?**
Did NOT touch mission.sqf but was in the process of porting presets to CUP Vehicles

**If yes, what did you edit exactly?**
Tried to replace MH-9 with UH-1 from CUP Vehicles (porting effort)

### Short Issue Description
Tail boom of UH-1 is long enough that it will cause automatic collision between both 'light' choppers due insufficient distance between said choppers.

### Expected Behaviour
Choppers not blowing up instantly.

### Steps to Reproduce the Issue
Spawn CUP_B_UH1Y_UNA_USMC or CUP_B_UH1D_GER_KSK as KPLIB_eden_rotary_light_1 | KPLIB_eden_rotary_light_0

### Screenshots, Serverlog or any other helpful Information
Screenshot for illustration (mega.nz cloud) : https://mega.nz/file/6VkCRKTB#RsNjmW6T0wyptqEOG9brr7fqy09B8IDl0fbqHniHOF4

**Comment by mwpowellhtx** [comment] 2023-05-31 18:04
Closing this one, thanks for the interest. This is by design, not designed to support larger rotary frames than the light ones in this regard. However, if you'd like to propose a change there, might I suggest you fork and submit a PR in the appropriate branch. Currently on `v0.98.dev-s31`, probably bumping to `v0.98.dev-s32` in the next day or so. You can find me here at _github_ or in one of the _discord_ forums in order to coordinate. Belated thank you, and thank you again for your interest.

**Closed as completed by mwpowellhtx** 2023-05-31 18:04 UTC
Labels: enhancement, wontfix
